### ISSUE TITLE
sounds/ambient/ceilingfan.ogg

### ISSUE THREAD

**Issue by stylemistake** [Warsow/warsow-assets#1]
This sound appears to be in free domain.

https://freesound.org/people/cognito%20perceptu/sounds/20350/

**Comment by qubodup** [comment]
Agreed, it's licensed under CC0 public domain dedication https://creativecommons.org/publicdomain/zero/1.0/

![image](https://user-images.githubusercontent.com/18312/62831586-4db30a80-bc22-11e9-8045-e6810af88845.png)
